// <auto-generated />
namespace FileCabinet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMark));
        
        string IMigrationMetadata.Id
        {
            get { return "201506111146460_addMark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
